<?php
/**
 * @file
 * Vantage page module.
 */

/**
 * Implements hook_node_info().
 */
function vantage_page_node_info() {
  return array(
    'page' => array(
      'name' => t('Page'),
      'base' => 'node_content',
      'description' => t('TODO: Describe this content type. The text will be displayed on the Add new content page.'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => t('TODO: This text will be displayed at the top of the page when creating or editing content of this type.'),
    ),
  );
}

/**
 * Implement hook_ctools_plugin_api().
 */
function vantage_page_ctools_plugin_api($module, $api) {
  if ($module == 'field_group' && $api == 'field_group') {
    return array('version' => 1);
  }
}

/**
 * Implementation of hook_default_template()
 */
function vantage_page_default_template() {
  $template_types = array();

  $template_type = new Template;
  $template_type->disabled = FALSE; /* Edit this to true to make a default template_type disabled initially */
  $template_type->name = 'vantage_one_column';
  $template_type->label = 'One column, unstyled';
  $template_type->tags = array(
    0 => 'page-template',
  );
  $template_type->renderer = 'mustache';
  $template_type->inputs = array(
    'content' => array(
      'label' => 'Content',
      'type' => 'text_format',
      'remove' => 0,
    ),
  );
  $template_type->content = '<div class="vantage-one-column">
  {{{ content }}}
  </div>';
  $template_type->attached = array(
    'js' => '',
    'css' => '',
    'libraries' => array(),
  );
  $template_types['vantage_one_column'] = $template_type;

  return $template_types;
}
